// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmmfhoupkxtqeexuhyzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbWZob3Vwa3h0cWVleHVoeXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzI5NTAsImV4cCI6MjA2ODUwODk1MH0.szp4kcmIhJwua2ZCl_Up35-QyKFFnu-ikT4sxN8H-po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});